/* Build src/data/usStates.ts: pre-projected state outlines for the
   national map. Source: us-atlas states-albers-10m (Census cartographic
   boundaries, already projected with geoAlbersUsa scale 1300, translate
   [487.5, 305]). Run: bun scripts/build-states.ts                      */
import { feature, mesh } from "topojson-client";
import { geoPath } from "d3-geo";
import type { Topology, GeometryCollection } from "topojson-specification";

const topo = (await Bun.file(new URL("../data-src/states-albers-10m.json", import.meta.url)).json()) as Topology;
const path = geoPath();
const round = (d: string | null) => (d ?? "").replace(/(\d+\.\d)\d+/g, "$1");

const states = feature(topo, topo.objects.states as GeometryCollection<{ name: string }>).features.map((f) => ({
  id: String(f.id),
  name: f.properties.name,
  d: round(path(f)),
}));
const borders = round(path(mesh(topo, topo.objects.states as GeometryCollection, (a, b) => a !== b)));
const nation = round(path(feature(topo, topo.objects.nation as GeometryCollection)));

const out = `/* GENERATED by scripts/build-states.ts from us-atlas states-albers-10m. Do not edit. */
export const US_VIEWBOX = "0 0 975 610";
export const US_NATION = ${JSON.stringify(nation)};
export const US_BORDERS = ${JSON.stringify(borders)};
export const US_STATES: { id: string; name: string; d: string }[] = ${JSON.stringify(states)};
`;
await Bun.write(new URL("../src/data/usStates.ts", import.meta.url), out);
console.log(states.length, "states,", (out.length / 1024).toFixed(0), "KB");
